package client;

import client.exceptions.InvalidDistrictException;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.*;

class MyCellRenderer extends DefaultTableCellRenderer {
  public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, java.lang.Object value, boolean isSelected, boolean hasFocus, int row, int column) {
    java.awt.Component cellComponent = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
    cellComponent.setBackground(java.awt.Color.BLUE);
    return cellComponent;
  }
}

public class MainPage {
  private JFrame frame;
  private JPanel panel;
  private JPanel dataPanel;
  private JPanel locationPanel;
  private JLabel name;
  private JLabel district;
  private JButton infectedButton;
  private JTextPane warningPane;
  private JLabel nPopulation;
  private JTable locationTable;

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  public void start() {
    this.frame = new JFrame("MainPage");
    frame.setContentPane(new MainPage().panel);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.setVisible(true);
  }

  public void quit() {
    frame.setVisible(false);
    frame.dispose();
  }

  public void setName(String name) {
    this.name.setText(name);
  }

  public void setDistrict(int districtNumber) {
    String district;
    switch (districtNumber) {
      case 1:
        district = "Aveiro";
        break;
      case 2:
        district = "Beja";
        break;
      case 3:
        district = "Braga";
        break;
      case 4:
        district = "Bragança";
        break;
      case 5:
        district = "Castelo Branco";
        break;
      case 6:
        district = "Coimbra";
        break;
      case 7:
        district = "Évora";
        break;
      case 8:
        district = "Faro";
        break;
      case 9:
        district = "Guarda";
        break;
      case 10:
        district = "Leiria";
        break;
      case 11:
        district = "Lisboa";
        break;
      case 12:
        district = "Portalegre";
        break;
      case 13:
        district = "Porto";
        break;
      case 14:
        district = "Santarém";
        break;
      case 15:
        district = "Setúbal";
        break;
      case 16:
        district = "Viana do Castelo";
        break;
      case 17:
        district = "Vila Real";
        break;
      case 18:
        district = "Viseu";
        break;
      default:
        district = "ERRO";
    }
    this.district.setText(district);
  }

  public void setWarning(String warning) {
    this.warningPane.setText(warning);
  }

  public void setUsersInLocation(int n) {
    this.nPopulation.setText(String.valueOf(n));
  }

  private void setSelectedCell(JTable table, int row, int column) {
    table.setRowSelectionInterval(row, row);
    table.setColumnSelectionInterval(column, column);
  }

  private void createUIComponents() {
    TableModel tableModel = new DefaultTableModel(10, 10) {
      @Override
      public boolean isCellEditable(int row, int column) {
        return false;
      }
    };
    locationTable = new JTable(tableModel);
    locationTable.setRowHeight(40);
    setSelectedCell(locationTable, 3, 6);

  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    panel = new JPanel();
    panel.setLayout(new GridBagLayout());
    panel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(50, 50, 50, 50), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
    dataPanel = new JPanel();
    dataPanel.setLayout(new GridBagLayout());
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.BOTH;
    panel.add(dataPanel, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.gridwidth = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 400;
    dataPanel.add(spacer1, gbc);
    final JLabel label1 = new JLabel();
    label1.setText("Nome:");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    dataPanel.add(label1, gbc);
    name = new JLabel();
    name.setText("João Carlos");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.gridwidth = 3;
    gbc.anchor = GridBagConstraints.WEST;
    dataPanel.add(name, gbc);
    final JLabel label2 = new JLabel();
    label2.setText("Distrito:");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 4;
    gbc.anchor = GridBagConstraints.WEST;
    dataPanel.add(label2, gbc);
    infectedButton = new JButton();
    infectedButton.setText("ESTOU INFETADO");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 9;
    gbc.gridwidth = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipady = 10;
    dataPanel.add(infectedButton, gbc);
    warningPane = new JTextPane();
    warningPane.setEditable(false);
    warningPane.setText("Nenhum contacto de risco detetado");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 7;
    gbc.gridwidth = 3;
    gbc.fill = GridBagConstraints.BOTH;
    gbc.ipady = 75;
    dataPanel.add(warningPane, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.gridwidth = 3;
    gbc.fill = GridBagConstraints.VERTICAL;
    dataPanel.add(spacer2, gbc);
    district = new JLabel();
    district.setText("Porto");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 4;
    gbc.anchor = GridBagConstraints.WEST;
    dataPanel.add(district, gbc);
    final JLabel label3 = new JLabel();
    label3.setText("População:");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 5;
    gbc.anchor = GridBagConstraints.WEST;
    dataPanel.add(label3, gbc);
    final JPanel spacer3 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 6;
    gbc.gridwidth = 3;
    gbc.fill = GridBagConstraints.VERTICAL;
    dataPanel.add(spacer3, gbc);
    nPopulation = new JLabel();
    nPopulation.setText("12345");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 5;
    gbc.anchor = GridBagConstraints.WEST;
    dataPanel.add(nPopulation, gbc);
    final JPanel spacer4 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 4;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    dataPanel.add(spacer4, gbc);
    final JPanel spacer5 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 8;
    gbc.gridwidth = 3;
    gbc.fill = GridBagConstraints.VERTICAL;
    dataPanel.add(spacer5, gbc);
    locationPanel = new JPanel();
    locationPanel.setLayout(new GridBagLayout());
    locationPanel.setEnabled(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.BOTH;
    panel.add(locationPanel, gbc);
    final JPanel spacer6 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 400;
    locationPanel.add(spacer6, gbc);
    final JLabel label4 = new JLabel();
    label4.setText("Localização");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    locationPanel.add(label4, gbc);
    final JPanel spacer7 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.VERTICAL;
    locationPanel.add(spacer7, gbc);
    locationTable.setCellSelectionEnabled(true);
    locationTable.setColumnSelectionAllowed(true);
    locationTable.setEditingColumn(-1);
    locationTable.setEnabled(true);
    locationTable.setFillsViewportHeight(true);
    locationTable.setFocusable(true);
    locationTable.setIntercellSpacing(new Dimension(1, 1));
    locationTable.setRowSelectionAllowed(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.BOTH;
    locationPanel.add(locationTable, gbc);
    final JPanel spacer8 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.gridheight = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel.add(spacer8, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return panel;
  }

}
